[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
explicit_package_bases = True

[mypy-zhipuai]
ignore_missing_imports = True

[mypy-faiss]
ignore_missing_imports = True

[mypy-PyPDF2.*]
ignore_missing_imports = True

[mypy-docx.*]
ignore_missing_imports = True
